name: CI build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check all links in *.md files
        id: lychee
        uses: lycheeverse/lychee-action@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >-
            -v -n "*.md" "**/*.md"
            --exclude "https://ingest.us0.signalfx.com.*"
            --exclude "http://localhost*"

      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build and test
        run: |
          echo "RUNNING TESTS"
          mkdir ~/testresults
          (cd /tmp; GO111MODULE=on go install gotest.tools/gotestsum@latest)
          CGO_ENABLED=0 gotestsum --format short-verbose --junitfile ~/testresults/unit.xml --raw-command -- go test --json -p 4 ./...
          echo "BUILDING"
          make
